In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = pd.read_csv('./train.csv', index_col='Id')
X_test_full = pd.read_csv('./test.csv', index_col='Id')

X.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
X.dropna(axis=0, subset=['SalePrice'], inplace=True)
y = X['SalePrice']
X.drop(['SalePrice'], axis=1, inplace=True)

print(X.shape)

X.head()

(1460, 79)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [4]:
print(y.shape)

y.head()

(1460,)

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

X_train_full, X_valid_full, y_train_full, y_valid_full = train_test_split(X, y, train_size=0.8, test_size=0.2)

print(X_train_full.shape)
print(X_valid_full.shape)
print(y_train_full.shape)
print(y_valid_full.shape)

(1168, 79)
(292, 79)
(1168,)
(292,)

In [10]:
low_cal_col = [cname for cname in X_train_full.columns if X_train_full[cname].nunique() < 10 and 
               X_train_full[cname].dtype == 'object']

low_cal_col  # columns which can be one-hot coded

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [11]:
numerical_col = [cname for cname in X_train_full.columns if X_train_full[cname].dtype in ['int64', 'float64']]

numerical_col

['MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold']

In [12]:
all_cols = low_cal_col + numerical_col

X_train = X_train_full[all_cols].copy()
X_valid = X_valid_full[all_cols].copy()
X_test = X_test_full[all_cols].copy()

In [13]:
# Pipeline for preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

numerical_transformer = SimpleImputer(strategy='mean')

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('one-hot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_col),
        ('cat', categorical_transformer, low_cal_col)
    ]
)

In [19]:
X_train.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Condition1,Condition2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
Id,,,,,,,,,,,,,,,,,,,,,
1288,RL,Pave,NaN,IR1,Low,AllPub,Inside,Mod,Norm,Norm,...,390,168,198,0,0,0,0,0,6,2006
925,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Norm,Norm,...,612,384,131,0,0,0,0,0,5,2006
38,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Norm,Norm,...,498,0,0,0,0,0,0,0,10,2009
1429,RM,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,Norm,Norm,...,240,0,0,154,0,0,0,0,2,2010
1344,RL,Pave,NaN,Reg,Bnk,AllPub,Inside,Gtl,Norm,Norm,...,342,0,0,0,0,0,0,0,3,2009

In [23]:
# Build the model
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error

model = XGBRegressor(n_estimators=1000, learning_rate=0.01)

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model)
])

pipeline.fit(X_train, y_train_full)

pred = pipeline.predict(X_valid)

mae = mean_absolute_error(y_valid_full, pred)

print("The MAE is:", mae)

The MAE is: 15342.876979880137

## Use cross Validation

In [ ]:
# Use cross validation
from sklearn.model_selection import cross_val_score

# Possible values for n_estimator
n_estimators_list = [100*i for i in range(10)]

for n in n_estimators_list:
    model_CV = XGBRegressor(n_estimators=n, learning_rate=0.01)
    
    pipeline_CV = Pipeline(steps=[
                        ('preprocessor', preprocessor),
                        ('model', model_CV)
                    ])

    
    scores = -1 * cross_val_score(pipeline_CV, X[all_cols], y,
                                 cv=5,
                                 scoring='neg_mean_absolute_error')
    
    print("Mean MAE score for n_estimator = {} is {}".format(n, scores.mean()))

Mean MAE score for n_estimator = 0 is 180920.69589041098
Mean MAE score for n_estimator = 100 is 68552.18020387416
Mean MAE score for n_estimator = 200 is 29550.866606913525
Mean MAE score for n_estimator = 300 is 19125.12356057363
Mean MAE score for n_estimator = 400 is 16959.605383133563
Mean MAE score for n_estimator = 500 is 16510.559864619005
Mean MAE score for n_estimator = 600 is 16351.3095703125
Mean MAE score for n_estimator = 700 is 16275.976364511986
Mean MAE score for n_estimator = 800 is 16231.218391481165